CTDA-984: Add Location header to MessageController in inbound router
hmrc/transit-movements-trader-router pull request #18
Opened 2020-12-16 15:35 UTC by jhkldev

2020-12-17 11:25 UTC, amaalali requested changes
The Location header isn't part of our contract with our upstream service so I don't believe that we should return an Internal Server Error. This would cause other major problems in production. Instead we can add logging, probably at warning level, that we can alerting for, if needed.

Additionally can we make the return statuses explicit in this controller. The dynamic responses to upstream base on the HttpResponses from downstream makes this hard to review

2020-12-17 11:25 UTC, amaalali commented on app/controllers/MessageController.scala
> +                    InternalServerError
I don't believe that this is the right status to return here, I believe that this should be Ok response with no header value for location

2020-12-21 14:15 UTC, crystalmark approved these changes

2020-12-21 16:38 UTC, amaalali approved these changes

2020-12-22 10:27 UTC, amaalali approved these changes

2020-12-22 10:31 UTC, merged